---

- include: "install/{{ansible_os_family}}.yml"

- name: Strongswan packages
  package:
    name: "{{item}}"
    state: present
  with_items: "{{strongswan_packages}}"
  register: _strongswan_pkgs

# vi:ts=2:sw=2:et:ft=yaml
